### ISSUE TITLE
Provide definition and/or suggested structure for ticket token

### ISSUE THREAD

**Issue by brylie** [finnishtransportagency/lippu-api#4]
In order to encourage a vendor-neurtal approach to ticket issuance, it would be helpful to specify/recommend a standard format for ticket tokens. That way, value added providers and integrators can have a consistent experience when booking tickets through various transportation providers.

**Comment by brylie** [comment]
cc @pippuri: does this accurately describe the issue?

**Comment by markkuko** [comment]
This was deliberately left out of scope for this project. There are currently many different formats is use and we dont want to force anyone to change/upgrade their validation machines.

**Comment by brylie** [comment]
> There are currently many different formats is use and we dont want to force anyone to change/upgrade their validation machines.

Understood. 

It is worth noting that ticket payload 'format proliferation' may somewhat defeat the purpose of standardizing the API structure. It has the effect that downstream developers need to handle proprietary, binary blobs for each transportation service provider.

**Comment by brylie** [comment]
As you referred to in issue #1, the BoB standard seems to offer guidance on ticket structure:

> The Mobile Ticket Format is designed to provide a uniform vehicle for mobile tickets from different
Participants. The aim is not to provide interoperability of tickets, but rather to provide a harmonisation
in how tickets are represented, encoded and signed with the goal of reducing costs in the
implementation of mobile ticketing solutions
>
>[Mobile Ticket Specifications – Mobile Ticket Format -  2.3. Ticket Bundle Mobile Ticket Specifications – Mobile Ticket Format (p4)](https://bitbucket.org/samtrafiken/bob/raw/04c3ec53e78449bd114277c3ff0a2f7216b8f597/spec/current/samtr-mts1-1.5.1.pdf)

**Comment by tulppux** [comment]
I think for a ticketing API to be useful, there should be at least principles towards the requirements for the ticket rendering set forth. Otherwise there is no interoperability and this is just encouraging the use of closed systems.

One key principle would be that the token would support a generic renderer on the client that is up to the client developer to implement. This is consistent with BoB, and how ticketing works in markets where there's a thriving ticket reseller ecosystem separate from the transport operator - UK, Netherlands, Switzerland for example. So if the purpose of this project is promoting interoperability and open market, there should be guidelines about this.

**Comment by pippuri** [comment]
I think for a ticketing API to be useful, there should be at least principles towards the requirements for the ticket rendering set forth. Otherwise there is no interoperability and this is just encouraging the use of closed systems.

One key principle would be that the token would support a generic renderer on the client that is up to the client developer to implement. This is consistent with BoB, and how ticketing works in markets where there's a thriving ticket reseller ecosystem separate from the transport operator - UK, Netherlands, Switzerland for example. So if the purpose of this project is promoting interoperability and open market, there should be guidelines about this.

**Comment by samulilahnamaki** [comment]
Yes, this was a recognized question and decision made after discussion with different transport operators. There are multitude of different ticket systems and validation methods fielded already and updating them to accept new formats would be expensive. In this API we turned this around so that transport service provider can provide ticket as it is used today and application developers to support all methods their partners have in use. (They are usually more agile to do so and its cheaper solution).

About ticket formats themselves they can be for example QR-code, pdf, image, PIN-code or other string, NFC message...

**Comment by brylie** [comment]
> There are multitude of different ticket systems and validation methods fielded already and updating them to accept new formats would be expensive. In this API we turned this around so that transport service provider can provide ticket as it is used today and application developers to support all methods their partners have in use.

That is understandable, particularly as a first step towards standardization. In the mid-to-long term, however, it seems reasonable to also standardize on a ticket payload. Intuitively however, it seems like there would be an order of magnitude more effort/expense if the burden is shifted to application developer ecosystem to cope with irregular data formats, rather than the encouraging transportation service providers to offer consistent data.

**Comment by pippuri** [comment]
As a step towards the direction, the project should encourage the use of open ticketing formats and implementations that don't place non-open rendering technologies into user agents. I think majority of Finnish ticketing systems are in line with this principle already (using QR codes, HTML, PDF presentation etc) so there should not be any technical reason for not doing this.

**Comment by markkuko** [comment]
> As you referred to in issue #1, the BoB standard seems to offer guidance on ticket structure:

Yes, they offer, but it is different standard with different goals. 

I understand the extra effort for the application developers, but as I wrote it is out of scope for this project.

**Comment by pippuri** [comment]
The law stipulates like this:

>  Lippu- ja maksujärjestelmien yhteentoimivuus
> 
> Tie- ja raideliikenteen henkilökuljetuspalvelun tarjoajan, välityspalvelun tarjoajan tai näiden puolesta lippu- ja maksujärjestelmästä vastaavan toimijan on avattava liikkumispalvelun tarjoajille ja yhdistämispalvelun tarjoajille pääsy lippu- ja maksujärjestelmänsä myyntirajapintaan, jonka kautta voi:
> 
> 1) hankkia vähintään perushintaisen kertamatkaan oikeuttavan lipputuotteen johon perustuvan matkustusoikeuden on oltava todennettavissa helpolla tavalla yleiskäyttöisen teknologian avulla; tai
> 
> 2) varata yksittäisen matkan tai kuljetuksen, jonka täsmällinen hinta ei ole tiedossa palvelun alkaessa tai joka muusta syystä sovitaan maksettavaksi palvelun päättymisen jälkeen.
> 

This "yleiskäyttöinen teknologia" is kind of the key here, so e.g. requiring proprietary binary blobs is not general purpose. This project should thus support the law and remind implementers about this.

**Comment by brylie** [comment]
@markkuko @pippuri, PR is open with changes to the **ticket format** section based on the *Laki liikenteen palveluista 320/2017 2 2 §*.

**Comment by markkuko** [comment]
Thank you for submitting the pull-request, we sent this for our project for a decision.

**Comment by markkuko** [comment]
Thank you for your input. Our interpretation is that the new law does not make requirements for a ticket format and allows all existing ticket products to exist. So this API will not mandate any particular ticket format. I'll close this issue now.

**Comment by brylie** [comment]
>  So this API will not mandate any particular ticket format.

To be clear, the pull request doest not propose that we mandate a particular format. Rather, the proposal is that we align with the word of the law by mandating **general-purpose technology (yleiskäyttöisen teknologian)**, a.k.a. **open standards (avoimet standardit)**. 

There is currently some difficulty with particular transportation service provider(s) who require downstream clients to use proprietary formats/libraries in their ticket rendering software, which may soon be illegal.

**Comment by samulilahnamaki** [comment]
This is a good note and while we don't want to force this in API, at least in this first phase, we will point this out to supervising authority. Thanks.
